<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <UserSecretsId>c38c8709-d8b1-43e6-8c6f-07b7a5c8fdca</UserSecretsId>
    <NoWarn>$(NoWarn);CS1591;CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Infrastructure\Database\Scripts\schema.sql" />
    <EmbeddedResource Include="Infrastructure\Database\Scripts\seed.sql" />
    <EmbeddedResource Include="Unit\Plans\*.xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Alyio.McpMssql\Alyio.McpMssql.csproj" />
  </ItemGroup>

</Project>
